# Generated by Django 5.1.6 on 2025-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('desired_pomodoro', models.IntegerField(default=0, null=True)),
                ('time_spent_today', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('schedule', models.JSONField()),
            ],
        ),
    ]
